---
- name: Add repository - Open-JDK
  apt_repository:
    repo: ppa:openjdk-r/ppa
    state: present
    update_cache: yes
  become: yes

- name: Update cache & install - Open-JDK
  apt:
    name: "{{ openjdk }}"
  become: yes

- name: Install unzip
  apt:
    name: unzip
  become: yes

- name: Create temporary installation directory
  tempfile:
    state: directory
    suffix: "_elasticsearch"
  register: elasticsearch_install_tmp_dir

- name: Download and add repository key - Open Distro for Elasticsearch
  apt_key:
    url: https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch
    state: present
  become: yes

- name: Add repository - Open Distro for Elasticsearch
  apt_repository:
    repo: deb https://d3g5vo6xdbdb9a.cloudfront.net/apt stable main
    state: present
    update_cache: yes
  become: yes

- name: Download Elasticsearch OSS
  get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/{{ oss }}-amd64.deb"
    dest: "{{ elasticsearch_install_tmp_dir['path'] }}"
  register: elasticsearch_oss_download

- name: Install Elasticsearch OSS
  apt:
    deb: "{{ elasticsearch_oss_download['dest'] }}"
    state: present
  become: yes

# Install mandatory plugins

- name: Install Elasticsearch OSS mandatory plugin - Security
  apt:
    name: "{{ security_plugin }}"
    state: present
  become: yes
  tags:
    - elasticsearch_oss_plugins

- name: Install Elasticsearch OSS mandatory plugin - Index Management
  apt:
    name: "{{ index_management_plugin }}"
    state: present
  become: yes
  tags:
    - elasticsearch_oss_plugins

# Install optional plugins

- name: Install Elasticsearch OSS optional plugin - Anomaly Detection
  apt:
    name: "{{ anomaly_detection_plugin }}"
    state: present
  become: yes
  when: anomaly_detection_install
  tags:
    - elasticsearch_oss_plugins

- name: Install Elasticsearch OSS optional plugin - Job Scheduler
  apt:
    name: "{{ job_scheduler_plugin }}"
    state: present
  become: yes
  when:
    - job_scheduler_install
    - anomaly_detection_install
  tags:
    - elasticsearch_oss_plugins

- name: Install Elasticsearch OSS optional plugin - KNN
  apt:
    name: "{{ knn_plugin }}"
    state: present
  become: yes
  when: knn_install
  tags:
    - elasticsearch_oss_plugins

- name: Install Elasticsearch OSS optional plugin - Alerting
  apt:
    name: "{{ alerting_plugin }}"
    state: present
  become: yes
  when: alerting_install
  tags:
    - elasticsearch_oss_plugins

- name: Install Elasticsearch OSS optional plugin - Performance Analyzer
  apt:
    name: "{{ performance_analyzer_plugin }}"
    state: present
  become: yes
  when: performance_analyzer_install
  tags:
    - elasticsearch_oss_plugins

- name: Install Elasticsearch OSS optional plugin - Opendistro SQL
  apt:
    name: "{{ sql_plugin }}"
    state: present
  become: yes
  when: sql_install
  tags:
    - elasticsearch_oss_plugins

- name: Start Elasticsearch
  service:
    name: elasticsearch.service
    state: started
    enabled: yes
  become: yes

- name: Test Elasticsearch post installation availability
  uri:
    url: https://localhost:9200
    method: GET
    url_username: "{{ default_admin }}"
    url_password: "{{ default_admin_password }}"
    validate_certs: no
  register: post_install_test
  tags:
    - test_elasticsearch_installation

- name: Display post-installation information
  debug:
    msg:
      - "Post-installation status:"
      - "{{ post_install_test.json }}"
      - "Status: {{ post_install_test.status }}"
  tags:
    - test_elasticsearch_installation